# Generated by Django 3.1.7 on 2021-03-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210330_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_yqsmou.jpg', upload_to='images/'),
        ),
    ]
